spring:
  profiles:
    active: 
    - dev
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: config-server-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka01.com:1001/eureka/
---
server:
  port: 6002
spring:
  profiles: test
  application:
    name: config-server-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka01.com:1001/eureka/